"""initial schema

Revision ID: 6a351acfbfb0
Revises: 
Create Date: 2026-04-06 21:50:03.529609

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a351acfbfb0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('elections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('election_type', sa.String(length=100), nullable=False),
    sa.Column('election_date', sa.Date(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('municipalities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('offices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('scope_type', sa.String(length=50), nullable=False),
    sa.Column('municipality_based', sa.Boolean(), nullable=False),
    sa.Column('required_positions', sa.Integer(), nullable=False),
    sa.Column('requires_parity', sa.Boolean(), nullable=False),
    sa.Column('requires_alternation', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('party_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dni', sa.String(length=20), nullable=False),
    sa.Column('affiliate_number', sa.String(length=50), nullable=True),
    sa.Column('first_name', sa.String(length=150), nullable=False),
    sa.Column('last_name', sa.String(length=150), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('source_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_party_members_dni'), 'party_members', ['dni'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'APODERADO', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('details_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('electoral_lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('election_id', sa.Integer(), nullable=False),
    sa.Column('office_id', sa.Integer(), nullable=False),
    sa.Column('municipality_id', sa.Integer(), nullable=True),
    sa.Column('list_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('BORRADOR', 'INCOMPLETA', 'EN_VALIDACION', 'RECHAZADA_COMPOSICION', 'APROBADA_SISTEMA', 'ENVIADA_ADMIN', name='liststatus'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['election_id'], ['elections.id'], ),
    sa.ForeignKeyConstraint(['municipality_id'], ['municipalities.id'], ),
    sa.ForeignKeyConstraint(['office_id'], ['offices.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_electoral_lists_election_id'), 'electoral_lists', ['election_id'], unique=False)
    op.create_index(op.f('ix_electoral_lists_municipality_id'), 'electoral_lists', ['municipality_id'], unique=False)
    op.create_index(op.f('ix_electoral_lists_office_id'), 'electoral_lists', ['office_id'], unique=False)
    op.create_table('persons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dni', sa.String(length=20), nullable=False),
    sa.Column('first_name', sa.String(length=150), nullable=False),
    sa.Column('last_name', sa.String(length=150), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('gender', sa.String(length=30), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('municipality_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['municipality_id'], ['municipalities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_persons_dni'), 'persons', ['dni'], unique=True)
    op.create_table('user_modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('election_id', sa.Integer(), nullable=False),
    sa.Column('office_id', sa.Integer(), nullable=False),
    sa.Column('municipality_id', sa.Integer(), nullable=True),
    sa.Column('module_type', sa.Enum('DIPUTADOS_PROVINCIALES', 'CONSEJOS_LOCALES', name='usermoduletype'), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['election_id'], ['elections.id'], ),
    sa.ForeignKeyConstraint(['municipality_id'], ['municipalities.id'], ),
    sa.ForeignKeyConstraint(['office_id'], ['offices.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_modules_election_id'), 'user_modules', ['election_id'], unique=False)
    op.create_index(op.f('ix_user_modules_municipality_id'), 'user_modules', ['municipality_id'], unique=False)
    op.create_index(op.f('ix_user_modules_office_id'), 'user_modules', ['office_id'], unique=False)
    op.create_index(op.f('ix_user_modules_user_id'), 'user_modules', ['user_id'], unique=False)
    op.create_table('candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.Column('office_id', sa.Integer(), nullable=False),
    sa.Column('election_id', sa.Integer(), nullable=False),
    sa.Column('candidate_status', sa.Enum('BORRADOR', 'PENDIENTE_VALIDACION', 'APROBADO_AUTOMATICAMENTE', 'RECHAZADO_AFILIACION', 'RECHAZADO_REQUISITOS', 'RECHAZADO_RENAPER', 'ERROR_INTEGRACION', name='candidatestatus'), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['election_id'], ['elections.id'], ),
    sa.ForeignKeyConstraint(['office_id'], ['offices.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidates_election_id'), 'candidates', ['election_id'], unique=False)
    op.create_index(op.f('ix_candidates_office_id'), 'candidates', ['office_id'], unique=False)
    op.create_index(op.f('ix_candidates_person_id'), 'candidates', ['person_id'], unique=False)
    op.create_table('list_validations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('validation_type', sa.Enum('AFILIACION', 'RENAPER', 'REQUISITOS_CARGO', 'COMPOSICION_LISTA', name='validationtype'), nullable=False),
    sa.Column('status', sa.Enum('OK', 'ERROR', 'PENDIENTE', name='validationresult'), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('response_json', sa.JSON(), nullable=True),
    sa.Column('validated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['list_id'], ['electoral_lists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_list_validations_list_id'), 'list_validations', ['list_id'], unique=False)
    op.create_table('candidate_validations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('validation_type', sa.Enum('AFILIACION', 'RENAPER', 'REQUISITOS_CARGO', 'COMPOSICION_LISTA', name='validationtype'), nullable=False),
    sa.Column('status', sa.Enum('OK', 'ERROR', 'PENDIENTE', name='validationresult'), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('response_json', sa.JSON(), nullable=True),
    sa.Column('validated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_validations_candidate_id'), 'candidate_validations', ['candidate_id'], unique=False)
    op.create_table('list_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('position_number', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=30), nullable=False),
    sa.Column('validated', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['list_id'], ['electoral_lists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_list_candidates_candidate_id'), 'list_candidates', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_list_candidates_list_id'), 'list_candidates', ['list_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_list_candidates_list_id'), table_name='list_candidates')
    op.drop_index(op.f('ix_list_candidates_candidate_id'), table_name='list_candidates')
    op.drop_table('list_candidates')
    op.drop_index(op.f('ix_candidate_validations_candidate_id'), table_name='candidate_validations')
    op.drop_table('candidate_validations')
    op.drop_index(op.f('ix_list_validations_list_id'), table_name='list_validations')
    op.drop_table('list_validations')
    op.drop_index(op.f('ix_candidates_person_id'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_office_id'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_election_id'), table_name='candidates')
    op.drop_table('candidates')
    op.drop_index(op.f('ix_user_modules_user_id'), table_name='user_modules')
    op.drop_index(op.f('ix_user_modules_office_id'), table_name='user_modules')
    op.drop_index(op.f('ix_user_modules_municipality_id'), table_name='user_modules')
    op.drop_index(op.f('ix_user_modules_election_id'), table_name='user_modules')
    op.drop_table('user_modules')
    op.drop_index(op.f('ix_persons_dni'), table_name='persons')
    op.drop_table('persons')
    op.drop_index(op.f('ix_electoral_lists_office_id'), table_name='electoral_lists')
    op.drop_index(op.f('ix_electoral_lists_municipality_id'), table_name='electoral_lists')
    op.drop_index(op.f('ix_electoral_lists_election_id'), table_name='electoral_lists')
    op.drop_table('electoral_lists')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_party_members_dni'), table_name='party_members')
    op.drop_table('party_members')
    op.drop_table('offices')
    op.drop_table('municipalities')
    op.drop_table('elections')
    # ### end Alembic commands ###
