"""secure sessions lockouts password recovery and mail outbox

Revision ID: 6cb192ebc9fe
Revises: e271bb89a403
Create Date: 2026-09-21 08:20:52.689580

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6cb192ebc9fe"
down_revision: Union[str, Sequence[str], None] = "e271bb89a403"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "auth_rate_limits",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("count", sa.Integer(), nullable=False),
        sa.Column("window_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_index(
        op.f("ix_auth_rate_limits_window_at"),
        "auth_rate_limits",
        ["window_at"],
        unique=False,
    )
    op.create_table(
        "auth_sessions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("last_used_at", sa.DateTime(), nullable=False),
        sa.Column("revoked_at", sa.DateTime(), nullable=True),
        sa.Column("reauthenticated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_auth_sessions_expires_at"),
        "auth_sessions",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_auth_sessions_user_id"), "auth_sessions", ["user_id"], unique=False
    )
    op.create_table(
        "mail_outbox",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("event_key", sa.String(length=150), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("payload", sa.Text(), nullable=True),
        sa.Column("reset_digest", sa.String(length=64), nullable=True),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("available_at", sa.DateTime(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("lease_id", sa.String(length=36), nullable=True),
        sa.Column("last_error", sa.String(length=80), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("event_key"),
    )
    op.create_index(
        op.f("ix_mail_outbox_available_at"),
        "mail_outbox",
        ["available_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_mail_outbox_state"), "mail_outbox", ["state"], unique=False
    )
    op.create_index(
        op.f("ix_mail_outbox_user_id"), "mail_outbox", ["user_id"], unique=False
    )
    op.create_table(
        "password_resets",
        sa.Column("digest", sa.String(length=64), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("credential_version", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("consumed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("digest"),
    )
    op.create_index(
        op.f("ix_password_resets_expires_at"),
        "password_resets",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_password_resets_user_id"), "password_resets", ["user_id"], unique=False
    )
    op.create_table(
        "refresh_credentials",
        sa.Column("digest", sa.String(length=64), nullable=False),
        sa.Column("session_id", sa.String(length=36), nullable=False),
        sa.Column("used_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["session_id"], ["auth_sessions.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("digest"),
    )
    op.create_index(
        op.f("ix_refresh_credentials_session_id"),
        "refresh_credentials",
        ["session_id"],
        unique=False,
    )
    op.add_column(
        "users",
        sa.Column("failed_attempts", sa.Integer(), server_default="0", nullable=False),
    )
    op.add_column("users", sa.Column("failure_window_at", sa.DateTime(), nullable=True))
    op.add_column("users", sa.Column("locked_until", sa.DateTime(), nullable=True))
    op.add_column(
        "users",
        sa.Column(
            "credential_version", sa.Integer(), server_default="0", nullable=False
        ),
    )
    op.add_column("users", sa.Column("last_recovery_at", sa.DateTime(), nullable=True))
    op.create_index(
        op.f("ix_users_locked_until"), "users", ["locked_until"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_locked_until"), table_name="users")
    op.drop_column("users", "last_recovery_at")
    op.drop_column("users", "credential_version")
    op.drop_column("users", "locked_until")
    op.drop_column("users", "failure_window_at")
    op.drop_column("users", "failed_attempts")
    op.drop_index(
        op.f("ix_refresh_credentials_session_id"), table_name="refresh_credentials"
    )
    op.drop_table("refresh_credentials")
    op.drop_index(op.f("ix_password_resets_user_id"), table_name="password_resets")
    op.drop_index(op.f("ix_password_resets_expires_at"), table_name="password_resets")
    op.drop_table("password_resets")
    op.drop_index(op.f("ix_mail_outbox_user_id"), table_name="mail_outbox")
    op.drop_index(op.f("ix_mail_outbox_state"), table_name="mail_outbox")
    op.drop_index(op.f("ix_mail_outbox_available_at"), table_name="mail_outbox")
    op.drop_table("mail_outbox")
    op.drop_index(op.f("ix_auth_sessions_user_id"), table_name="auth_sessions")
    op.drop_index(op.f("ix_auth_sessions_expires_at"), table_name="auth_sessions")
    op.drop_table("auth_sessions")
    op.drop_index(op.f("ix_auth_rate_limits_window_at"), table_name="auth_rate_limits")
    op.drop_table("auth_rate_limits")
    # ### end Alembic commands ###
