"""add affiliate import batches and update party members

Revision ID: 72cd9f9655de
Revises: 6a351acfbfb0
Create Date: 2026-04-21 20:11:20.809537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72cd9f9655de'
down_revision: Union[str, Sequence[str], None] = '6a351acfbfb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('affiliate_import_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('imported_by', sa.Integer(), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('valid_rows', sa.Integer(), nullable=False),
    sa.Column('invalid_rows', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('imported_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['imported_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_affiliate_import_batches_id'), 'affiliate_import_batches', ['id'], unique=False)
    op.create_index(op.f('ix_affiliate_import_batches_imported_by'), 'affiliate_import_batches', ['imported_by'], unique=False)
    op.add_column('party_members', sa.Column('full_name', sa.String(length=255), nullable=False))
    op.add_column('party_members', sa.Column('normalized_name', sa.String(length=255), nullable=False))
    op.add_column('party_members', sa.Column('gender', sa.String(length=30), nullable=True))
    op.add_column('party_members', sa.Column('section', sa.String(length=100), nullable=True))
    op.add_column('party_members', sa.Column('circuit', sa.String(length=100), nullable=True))
    op.add_column('party_members', sa.Column('affiliation_status', sa.String(length=50), nullable=False))
    op.add_column('party_members', sa.Column('affiliation_date', sa.Date(), nullable=True))
    op.add_column('party_members', sa.Column('source_batch_id', sa.Integer(), nullable=False))
    op.add_column('party_members', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('party_members', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.drop_index(op.f('ix_party_members_dni'), table_name='party_members')
    op.create_index(op.f('ix_party_members_dni'), 'party_members', ['dni'], unique=False)
    op.create_index(op.f('ix_party_members_id'), 'party_members', ['id'], unique=False)
    op.create_index(op.f('ix_party_members_normalized_name'), 'party_members', ['normalized_name'], unique=False)
    op.create_index(op.f('ix_party_members_source_batch_id'), 'party_members', ['source_batch_id'], unique=False)
    op.create_foreign_key(None, 'party_members', 'affiliate_import_batches', ['source_batch_id'], ['id'])
    op.drop_column('party_members', 'status')
    op.drop_column('party_members', 'source_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('party_members', sa.Column('source_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('party_members', sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'party_members', type_='foreignkey')
    op.drop_index(op.f('ix_party_members_source_batch_id'), table_name='party_members')
    op.drop_index(op.f('ix_party_members_normalized_name'), table_name='party_members')
    op.drop_index(op.f('ix_party_members_id'), table_name='party_members')
    op.drop_index(op.f('ix_party_members_dni'), table_name='party_members')
    op.create_index(op.f('ix_party_members_dni'), 'party_members', ['dni'], unique=True)
    op.drop_column('party_members', 'created_at')
    op.drop_column('party_members', 'is_active')
    op.drop_column('party_members', 'source_batch_id')
    op.drop_column('party_members', 'affiliation_date')
    op.drop_column('party_members', 'affiliation_status')
    op.drop_column('party_members', 'circuit')
    op.drop_column('party_members', 'section')
    op.drop_column('party_members', 'gender')
    op.drop_column('party_members', 'normalized_name')
    op.drop_column('party_members', 'full_name')
    op.drop_index(op.f('ix_affiliate_import_batches_imported_by'), table_name='affiliate_import_batches')
    op.drop_index(op.f('ix_affiliate_import_batches_id'), table_name='affiliate_import_batches')
    op.drop_table('affiliate_import_batches')
    # ### end Alembic commands ###
