"""add list role definitions and update list candidates

Revision ID: 734865b8795b
Revises: 72cd9f9655de
Create Date: 2026-05-06 22:12:04.904040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '734865b8795b'
down_revision: Union[str, Sequence[str], None] = '72cd9f9655de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('list_role_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('office_type', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('group_name', sa.String(length=100), nullable=False),
    sa.Column('position_order', sa.Integer(), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('gender_rule', sa.String(length=30), nullable=True),
    sa.Column('is_titular', sa.Boolean(), nullable=False),
    sa.Column('is_suplente', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index(op.f('ix_list_role_definitions_id'), 'list_role_definitions', ['id'], unique=False)
    op.create_index(op.f('ix_list_role_definitions_office_type'), 'list_role_definitions', ['office_type'], unique=False)
    op.add_column('list_candidates', sa.Column('role_definition_id', sa.Integer(), nullable=True))
    op.add_column('list_candidates', sa.Column('cargo_label', sa.String(length=150), nullable=False))
    op.add_column('list_candidates', sa.Column('cargo_group', sa.String(length=100), nullable=False))
    op.add_column('list_candidates', sa.Column('is_validated', sa.Boolean(), nullable=False))
    op.add_column('list_candidates', sa.Column('validation_summary', sa.Text(), nullable=True))
    op.create_index(op.f('ix_list_candidates_id'), 'list_candidates', ['id'], unique=False)
    op.create_index(op.f('ix_list_candidates_role_definition_id'), 'list_candidates', ['role_definition_id'], unique=False)
    op.create_foreign_key(None, 'list_candidates', 'list_role_definitions', ['role_definition_id'], ['id'])
    op.drop_column('list_candidates', 'validated')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('list_candidates', sa.Column('validated', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'list_candidates', type_='foreignkey')
    op.drop_index(op.f('ix_list_candidates_role_definition_id'), table_name='list_candidates')
    op.drop_index(op.f('ix_list_candidates_id'), table_name='list_candidates')
    op.drop_column('list_candidates', 'validation_summary')
    op.drop_column('list_candidates', 'is_validated')
    op.drop_column('list_candidates', 'cargo_group')
    op.drop_column('list_candidates', 'cargo_label')
    op.drop_column('list_candidates', 'role_definition_id')
    op.drop_index(op.f('ix_list_role_definitions_office_type'), table_name='list_role_definitions')
    op.drop_index(op.f('ix_list_role_definitions_id'), table_name='list_role_definitions')
    op.drop_table('list_role_definitions')
    # ### end Alembic commands ###
