"""electoral configuration assignments and official register

Revision ID: dc5da19db749
Revises: 8c4f2e91b6a7
Create Date: 2026-09-20 21:28:58.772622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc5da19db749'
down_revision: Union[str, Sequence[str], None] = '8c4f2e91b6a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('election_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('election_id', sa.Integer(), nullable=False),
    sa.Column('office_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('rules', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['election_id'], ['elections.id'], ),
    sa.ForeignKeyConstraint(['office_id'], ['offices.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('election_id', 'office_id', 'version')
    )
    op.create_index(op.f('ix_election_rules_election_id'), 'election_rules', ['election_id'], unique=False)
    op.create_index(op.f('ix_election_rules_office_id'), 'election_rules', ['office_id'], unique=False)
    op.create_table('list_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('list_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['list_id'], ['electoral_lists.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('list_id', 'user_id')
    )
    op.create_index(op.f('ix_list_assignments_list_id'), 'list_assignments', ['list_id'], unique=False)
    op.create_index(op.f('ix_list_assignments_user_id'), 'list_assignments', ['user_id'], unique=False)
    op.add_column('candidate_validations', sa.Column('candidate_revision', sa.Integer(), nullable=True))
    op.add_column('candidates', sa.Column('revision', sa.Integer(), server_default='1', nullable=False))
    op.add_column('elections', sa.Column('loading_opens', sa.Date(), nullable=True))
    op.add_column('elections', sa.Column('loading_closes', sa.Date(), nullable=True))
    op.add_column('electoral_lists', sa.Column('list_number', sa.String(length=40), nullable=True))
    op.add_column('electoral_lists', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('electoral_lists', sa.Column('rule_version_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_list_rule_version', 'electoral_lists', 'election_rules', ['rule_version_id'], ['id'])
    op.add_column('party_members', sa.Column('section_code', sa.String(length=50), nullable=True))
    op.add_column('party_members', sa.Column('circuit_code', sa.String(length=50), nullable=True))
    op.add_column('party_members', sa.Column('document_type', sa.String(length=50), nullable=True))
    op.add_column('party_members', sa.Column('birth_date', sa.Date(), nullable=True))
    op.add_column('party_members', sa.Column('birth_class', sa.String(length=20), nullable=True))
    op.add_column('party_members', sa.Column('elector_status', sa.String(length=100), nullable=True))
    op.add_column('party_members', sa.Column('illiterate', sa.String(length=30), nullable=True))
    op.add_column('party_members', sa.Column('profession', sa.String(length=150), nullable=True))
    op.add_column('party_members', sa.Column('address_date', sa.Date(), nullable=True))
    op.add_column('party_members', sa.Column('address', sa.String(length=255), nullable=True))
    op.execute("INSERT INTO list_assignments (list_id, user_id) SELECT l.id, l.created_by FROM electoral_lists l JOIN users u ON u.id=l.created_by WHERE u.role='APODERADO'")
    # Existing admin-created lists require an explicit assignment; dates/rules stay unconfigured.
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('party_members', 'address')
    op.drop_column('party_members', 'address_date')
    op.drop_column('party_members', 'profession')
    op.drop_column('party_members', 'illiterate')
    op.drop_column('party_members', 'elector_status')
    op.drop_column('party_members', 'birth_class')
    op.drop_column('party_members', 'birth_date')
    op.drop_column('party_members', 'document_type')
    op.drop_column('party_members', 'circuit_code')
    op.drop_column('party_members', 'section_code')
    op.drop_constraint('fk_list_rule_version', 'electoral_lists', type_='foreignkey')
    op.drop_column('electoral_lists', 'rule_version_id')
    op.drop_column('electoral_lists', 'created_at')
    op.drop_column('electoral_lists', 'list_number')
    op.drop_column('elections', 'loading_closes')
    op.drop_column('elections', 'loading_opens')
    op.drop_column('candidates', 'revision')
    op.drop_column('candidate_validations', 'candidate_revision')
    op.drop_index(op.f('ix_list_assignments_user_id'), table_name='list_assignments')
    op.drop_index(op.f('ix_list_assignments_list_id'), table_name='list_assignments')
    op.drop_table('list_assignments')
    op.drop_index(op.f('ix_election_rules_office_id'), table_name='election_rules')
    op.drop_index(op.f('ix_election_rules_election_id'), table_name='election_rules')
    op.drop_table('election_rules')
    # ### end Alembic commands ###
